### ISSUE TITLE
Запросы с параметром text

### ISSUE THREAD

**Issue by ad-Ham** [ivbeg/readability.io#10]
Добрый день! Пытаюсь запустить ваш пример запроса к API на python, однако возвращает 400 Bad Request. Подскажите в каком формате в запрос должен передавать кириллический текст, чтобы можно было отправить запрос через requests.get().

**Comment by ivbeg** [comment]
Нужно передавать text через запрос POST. В Python это requests.post()

**Comment by ad-Ham** [comment]
Именно так и передаю, однако все равно возвращает Bad request

**Comment by ivbeg** [comment]
Это очень странно, я рекомендую отлаживать не в коде, а в инструментах вроде Postman.


Работающий пример кода на Python
```
import requests

url = "https://api.plainrussian.ru/api/1.0/ru/measure/"

payload={'text': 'Этот текст написан для проверки системы проверки текстов.'}
files=[

]
headers = {}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
```

**Comment by ad-Ham** [comment]
Спасибо большое, таким образом работает.
