### ISSUE TITLE
Возвращает ошибку 400

### ISSUE THREAD

**Issue by oldaandozerskaya** [ivbeg/readability.io#8]
Добрый день!

Предложенный пример возвращает ошибку сервера. Скажите, пожалуйста, будет ли она устранена?

![изображение](https://user-images.githubusercontent.com/46136261/128681033-7aa11e2d-07a0-4b92-be17-2256b003dbd5.png)

**Comment by ivbeg** [comment]
@oldaandozerskaya добрый день, замените на https и всё должно работать

**Comment by oldaandozerskaya** [comment]
Спасибо, работает!
