### ISSUE TITLE
Не работает api

### ISSUE THREAD

**Issue by keksum666** [ivbeg/readability.io#9]
Добрый день, не работает api с текстом.
Воспроизведение:
Отправка запроса на url: http://api.plainrussian.ru/api/1.0/ru/measure
Тип запроса: POST
Тело запроса: {"text": "Пробный текст"}

Ответ: 400 - Bad request
Заранее спасибо)

**Comment by keksum666** [comment]
Также пробовал вместо http использовать https
Запросы выполнялись через postman

**Comment by ivbeg** [comment]
POST запрос принимает не JSON, а параметры.

**Comment by keksum666** [comment]
Ага, спасибо помогло)
